//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBA.SVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC.IBD")]
    public interface IBD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        bool ConectarBD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        System.Threading.Tasks.Task<bool> ConectarBDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        PRUEBA.SVC.ListarDatosResponse ListarDatos(PRUEBA.SVC.ListarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        System.Threading.Tasks.Task<PRUEBA.SVC.ListarDatosResponse> ListarDatosAsync(PRUEBA.SVC.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/FiltrarDatos", ReplyAction="http://tempuri.org/IBD/FiltrarDatosResponse")]
        PRUEBA.SVC.FiltrarDatosResponse FiltrarDatos(PRUEBA.SVC.FiltrarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/FiltrarDatos", ReplyAction="http://tempuri.org/IBD/FiltrarDatosResponse")]
        System.Threading.Tasks.Task<PRUEBA.SVC.FiltrarDatosResponse> FiltrarDatosAsync(PRUEBA.SVC.FiltrarDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNobreSP, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string sMsjError) {
            this.ListarDatosResult = ListarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.SqlDbType DbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sValorParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sMsjError;
        
        public FiltrarDatosRequest() {
        }
        
        public FiltrarDatosRequest(string sNobreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.sNombreParametro = sNombreParametro;
            this.DbType = DbType;
            this.sValorParametro = sValorParametro;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable FiltrarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public FiltrarDatosResponse() {
        }
        
        public FiltrarDatosResponse(System.Data.DataTable FiltrarDatosResult, string sMsjError) {
            this.FiltrarDatosResult = FiltrarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDChannel : PRUEBA.SVC.IBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDClient : System.ServiceModel.ClientBase<PRUEBA.SVC.IBD>, PRUEBA.SVC.IBD {
        
        public BDClient() {
        }
        
        public BDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConectarBD() {
            return base.Channel.ConectarBD();
        }
        
        public System.Threading.Tasks.Task<bool> ConectarBDAsync() {
            return base.Channel.ConectarBDAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRUEBA.SVC.ListarDatosResponse PRUEBA.SVC.IBD.ListarDatos(PRUEBA.SVC.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNobreSP, ref string sMsjError) {
            PRUEBA.SVC.ListarDatosRequest inValue = new PRUEBA.SVC.ListarDatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.sMsjError = sMsjError;
            PRUEBA.SVC.ListarDatosResponse retVal = ((PRUEBA.SVC.IBD)(this)).ListarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<PRUEBA.SVC.ListarDatosResponse> ListarDatosAsync(PRUEBA.SVC.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRUEBA.SVC.FiltrarDatosResponse PRUEBA.SVC.IBD.FiltrarDatos(PRUEBA.SVC.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatos(request);
        }
        
        public System.Data.DataTable FiltrarDatos(string sNobreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, ref string sMsjError) {
            PRUEBA.SVC.FiltrarDatosRequest inValue = new PRUEBA.SVC.FiltrarDatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.sNombreParametro = sNombreParametro;
            inValue.DbType = DbType;
            inValue.sValorParametro = sValorParametro;
            inValue.sMsjError = sMsjError;
            PRUEBA.SVC.FiltrarDatosResponse retVal = ((PRUEBA.SVC.IBD)(this)).FiltrarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.FiltrarDatosResult;
        }
        
        public System.Threading.Tasks.Task<PRUEBA.SVC.FiltrarDatosResponse> FiltrarDatosAsync(PRUEBA.SVC.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatosAsync(request);
        }
    }
}
