//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.SVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC.IBD")]
    public interface IBD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        bool ConectarBD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ConectarBD", ReplyAction="http://tempuri.org/IBD/ConectarBDResponse")]
        System.Threading.Tasks.Task<bool> ConectarBDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        BLL.SVC.ListarDatosResponse ListarDatos(BLL.SVC.ListarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        System.Threading.Tasks.Task<BLL.SVC.ListarDatosResponse> ListarDatosAsync(BLL.SVC.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/FiltrarDatos", ReplyAction="http://tempuri.org/IBD/FiltrarDatosResponse")]
        BLL.SVC.FiltrarDatosResponse FiltrarDatos(BLL.SVC.FiltrarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/FiltrarDatos", ReplyAction="http://tempuri.org/IBD/FiltrarDatosResponse")]
        System.Threading.Tasks.Task<BLL.SVC.FiltrarDatosResponse> FiltrarDatosAsync(BLL.SVC.FiltrarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Inserta_DatosSinIdentity", ReplyAction="http://tempuri.org/IBD/Inserta_DatosSinIdentityResponse")]
        BLL.SVC.Inserta_DatosSinIdentityResponse Inserta_DatosSinIdentity(BLL.SVC.Inserta_DatosSinIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Inserta_DatosSinIdentity", ReplyAction="http://tempuri.org/IBD/Inserta_DatosSinIdentityResponse")]
        System.Threading.Tasks.Task<BLL.SVC.Inserta_DatosSinIdentityResponse> Inserta_DatosSinIdentityAsync(BLL.SVC.Inserta_DatosSinIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/InsertaDatosConIdentity", ReplyAction="http://tempuri.org/IBD/InsertaDatosConIdentityResponse")]
        BLL.SVC.InsertaDatosConIdentityResponse InsertaDatosConIdentity(BLL.SVC.InsertaDatosConIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/InsertaDatosConIdentity", ReplyAction="http://tempuri.org/IBD/InsertaDatosConIdentityResponse")]
        System.Threading.Tasks.Task<BLL.SVC.InsertaDatosConIdentityResponse> InsertaDatosConIdentityAsync(BLL.SVC.InsertaDatosConIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Modifica_Datos", ReplyAction="http://tempuri.org/IBD/Modifica_DatosResponse")]
        BLL.SVC.Modifica_DatosResponse Modifica_Datos(BLL.SVC.Modifica_DatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Modifica_Datos", ReplyAction="http://tempuri.org/IBD/Modifica_DatosResponse")]
        System.Threading.Tasks.Task<BLL.SVC.Modifica_DatosResponse> Modifica_DatosAsync(BLL.SVC.Modifica_DatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Elimina_Datos", ReplyAction="http://tempuri.org/IBD/Elimina_DatosResponse")]
        BLL.SVC.Elimina_DatosResponse Elimina_Datos(BLL.SVC.Elimina_DatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Elimina_Datos", ReplyAction="http://tempuri.org/IBD/Elimina_DatosResponse")]
        System.Threading.Tasks.Task<BLL.SVC.Elimina_DatosResponse> Elimina_DatosAsync(BLL.SVC.Elimina_DatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNobreSP, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string sMsjError) {
            this.ListarDatosResult = ListarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.SqlDbType DbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sValorParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sMsjError;
        
        public FiltrarDatosRequest() {
        }
        
        public FiltrarDatosRequest(string sNobreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.sNombreParametro = sNombreParametro;
            this.DbType = DbType;
            this.sValorParametro = sValorParametro;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable FiltrarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public FiltrarDatosResponse() {
        }
        
        public FiltrarDatosResponse(System.Data.DataTable FiltrarDatosResult, string sMsjError) {
            this.FiltrarDatosResult = FiltrarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Inserta_DatosSinIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Inserta_DatosSinIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Inserta_DatosSinIdentityRequest() {
        }
        
        public Inserta_DatosSinIdentityRequest(string sNobreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Inserta_DatosSinIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Inserta_DatosSinIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Inserta_DatosSinIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Inserta_DatosSinIdentityResponse() {
        }
        
        public Inserta_DatosSinIdentityResponse(bool Inserta_DatosSinIdentityResult, string sMsjError) {
            this.Inserta_DatosSinIdentityResult = Inserta_DatosSinIdentityResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertaDatosConIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertaDatosConIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sMsjError;
        
        public InsertaDatosConIdentityRequest() {
        }
        
        public InsertaDatosConIdentityRequest(string sNobreSP, System.Data.DataTable dtParametros, string sValorScalar, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.dtParametros = dtParametros;
            this.sValorScalar = sValorScalar;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertaDatosConIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertaDatosConIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertaDatosConIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public InsertaDatosConIdentityResponse() {
        }
        
        public InsertaDatosConIdentityResponse(bool InsertaDatosConIdentityResult, string sValorScalar, string sMsjError) {
            this.InsertaDatosConIdentityResult = InsertaDatosConIdentityResult;
            this.sValorScalar = sValorScalar;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Modifica_DatosRequest() {
        }
        
        public Modifica_DatosRequest(string sNobreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Modifica_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Modifica_DatosResponse() {
        }
        
        public Modifica_DatosResponse(bool Modifica_DatosResult, string sMsjError) {
            this.Modifica_DatosResult = Modifica_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elimina_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Elimina_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNobreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public Elimina_DatosRequest() {
        }
        
        public Elimina_DatosRequest(string sNobreSP, System.Data.DataTable dtParametros, string sMsjError) {
            this.sNobreSP = sNobreSP;
            this.dtParametros = dtParametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elimina_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Elimina_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Elimina_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Elimina_DatosResponse() {
        }
        
        public Elimina_DatosResponse(bool Elimina_DatosResult, string sMsjError) {
            this.Elimina_DatosResult = Elimina_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDChannel : BLL.SVC.IBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDClient : System.ServiceModel.ClientBase<BLL.SVC.IBD>, BLL.SVC.IBD {
        
        public BDClient() {
        }
        
        public BDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConectarBD() {
            return base.Channel.ConectarBD();
        }
        
        public System.Threading.Tasks.Task<bool> ConectarBDAsync() {
            return base.Channel.ConectarBDAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.ListarDatosResponse BLL.SVC.IBD.ListarDatos(BLL.SVC.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNobreSP, ref string sMsjError) {
            BLL.SVC.ListarDatosRequest inValue = new BLL.SVC.ListarDatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.sMsjError = sMsjError;
            BLL.SVC.ListarDatosResponse retVal = ((BLL.SVC.IBD)(this)).ListarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.ListarDatosResponse> ListarDatosAsync(BLL.SVC.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.FiltrarDatosResponse BLL.SVC.IBD.FiltrarDatos(BLL.SVC.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatos(request);
        }
        
        public System.Data.DataTable FiltrarDatos(string sNobreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValorParametro, ref string sMsjError) {
            BLL.SVC.FiltrarDatosRequest inValue = new BLL.SVC.FiltrarDatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.sNombreParametro = sNombreParametro;
            inValue.DbType = DbType;
            inValue.sValorParametro = sValorParametro;
            inValue.sMsjError = sMsjError;
            BLL.SVC.FiltrarDatosResponse retVal = ((BLL.SVC.IBD)(this)).FiltrarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.FiltrarDatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.FiltrarDatosResponse> FiltrarDatosAsync(BLL.SVC.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.Inserta_DatosSinIdentityResponse BLL.SVC.IBD.Inserta_DatosSinIdentity(BLL.SVC.Inserta_DatosSinIdentityRequest request) {
            return base.Channel.Inserta_DatosSinIdentity(request);
        }
        
        public bool Inserta_DatosSinIdentity(string sNobreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            BLL.SVC.Inserta_DatosSinIdentityRequest inValue = new BLL.SVC.Inserta_DatosSinIdentityRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            BLL.SVC.Inserta_DatosSinIdentityResponse retVal = ((BLL.SVC.IBD)(this)).Inserta_DatosSinIdentity(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Inserta_DatosSinIdentityResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.Inserta_DatosSinIdentityResponse> Inserta_DatosSinIdentityAsync(BLL.SVC.Inserta_DatosSinIdentityRequest request) {
            return base.Channel.Inserta_DatosSinIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.InsertaDatosConIdentityResponse BLL.SVC.IBD.InsertaDatosConIdentity(BLL.SVC.InsertaDatosConIdentityRequest request) {
            return base.Channel.InsertaDatosConIdentity(request);
        }
        
        public bool InsertaDatosConIdentity(string sNobreSP, System.Data.DataTable dtParametros, ref string sValorScalar, ref string sMsjError) {
            BLL.SVC.InsertaDatosConIdentityRequest inValue = new BLL.SVC.InsertaDatosConIdentityRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.dtParametros = dtParametros;
            inValue.sValorScalar = sValorScalar;
            inValue.sMsjError = sMsjError;
            BLL.SVC.InsertaDatosConIdentityResponse retVal = ((BLL.SVC.IBD)(this)).InsertaDatosConIdentity(inValue);
            sValorScalar = retVal.sValorScalar;
            sMsjError = retVal.sMsjError;
            return retVal.InsertaDatosConIdentityResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.InsertaDatosConIdentityResponse> InsertaDatosConIdentityAsync(BLL.SVC.InsertaDatosConIdentityRequest request) {
            return base.Channel.InsertaDatosConIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.Modifica_DatosResponse BLL.SVC.IBD.Modifica_Datos(BLL.SVC.Modifica_DatosRequest request) {
            return base.Channel.Modifica_Datos(request);
        }
        
        public bool Modifica_Datos(string sNobreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            BLL.SVC.Modifica_DatosRequest inValue = new BLL.SVC.Modifica_DatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            BLL.SVC.Modifica_DatosResponse retVal = ((BLL.SVC.IBD)(this)).Modifica_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Modifica_DatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.Modifica_DatosResponse> Modifica_DatosAsync(BLL.SVC.Modifica_DatosRequest request) {
            return base.Channel.Modifica_DatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.SVC.Elimina_DatosResponse BLL.SVC.IBD.Elimina_Datos(BLL.SVC.Elimina_DatosRequest request) {
            return base.Channel.Elimina_Datos(request);
        }
        
        public bool Elimina_Datos(string sNobreSP, System.Data.DataTable dtParametros, ref string sMsjError) {
            BLL.SVC.Elimina_DatosRequest inValue = new BLL.SVC.Elimina_DatosRequest();
            inValue.sNobreSP = sNobreSP;
            inValue.dtParametros = dtParametros;
            inValue.sMsjError = sMsjError;
            BLL.SVC.Elimina_DatosResponse retVal = ((BLL.SVC.IBD)(this)).Elimina_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Elimina_DatosResult;
        }
        
        public System.Threading.Tasks.Task<BLL.SVC.Elimina_DatosResponse> Elimina_DatosAsync(BLL.SVC.Elimina_DatosRequest request) {
            return base.Channel.Elimina_DatosAsync(request);
        }
    }
}
